version: "3.7"
services:
  murmur:
    image: znibb/murmur:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "64738:64738" # client
      - "6502:6502"   # ICE
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "data:/murmur"
    configs:
      - source: murmur_config_v1
        target: /murmur/murmur.conf
        uid: '100'
        gid: '101'
        mode: 0644
    secrets:
      - source: murmur_su_pw
        target: SU_PW
        uid: '100'
        gid: '101'
        mode: 0400
    networks:
      - murmur

volumes:
  data:
    driver: local

configs:
  murmur_config_v1:
    external: true

secrets:
  murmur_su_pw:
    external: true

networks:
  murmur:
